version: '3.8'

services:
  backend:
    image: myapp_backend
    ports:
      - "3001:3001"
    networks:
      - cimsi_app_network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatApp
      - CORS_ORIGIN=http://localhost:5173,http://frontend:5173,http://172.18.0.2:5173,http://135.236.97.129

  frontend:
    image: myapp_frontend
    ports:
      - "5173:5173"
    networks:
      - cimsi_app_network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: myapp_nginx 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map your custom Nginx config
    ports:
      - "80:80"
    networks:
      - cimsi_app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - cimsi_app_network
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  mongo-seed:
    image: mongo_seed
    depends_on:
      - mongo
    networks:
      - cimsi_app_network
    deploy:
      replicas: 1

volumes:
  mongo_data:

networks:
  cimsi_app_network:
    driver: overlay

